### PR TITLE
Fix query to handle nil ImageSetID

### PR DESCRIPTION
**Pull request by Avielyo10**
# Description

When ImageSetID is `nil` the SQL query is calling `image_set_id = NULL` which is invalid syntax (should be `image_set_id is NULL`).

This caused the image to not be found.

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Review by biancarosa — APPROVED** [review]

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Pull request merged**
