### PR TITLE
remove fdo routes

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
# Description
Remove FDO routes from code

FIXES: HMS-4010

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

### CODE REVIEW

**Comment by loadtheaccumulator** [comment]
We can consider deprecation of the endpoints with a deprecation header and maybe 409 Gone--then execute on this removal in the future.

**Comment by lzap** [comment]
LGTM

**Comment by lzap** [comment]
Can you also add a migration to remove those tables from the DB? Or if you prefer to do it separately, I think thanks to the automigrate the database is in bad shape and we should do a thorough review and remove all fields/tables/indicies which are not used.

**Comment by loadtheaccumulator** [comment]
> Can you also add a migration to remove those tables from the DB? Or if you prefer to do it separately, I think thanks to the automigrate the database is in bad shape and we should do a thorough review and remove all fields/tables/indicies which are not used.

Yeah. I'll do that in an additional PR. +1 on review of tables and fields

**Comment by loadtheaccumulator** [comment]
Also confirmed with RHEL for Edge team this code is no longer required. I'll merge and test in stage in the AM.

**Pull request merged**
