### PR TITLE
Do not state the obvious

### PR DESCRIPTION
**Pull request by ezr-ondrej**
# Description

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Ya okay dude? :-)

**Comment by ezr-ondrej** [comment]
I'm testing Konflux on this xD I was thinking hard what change to introduce xD

**Pull request closed without merging**
