### PR TITLE
Drop and make account Nullable for image_set

### PR DESCRIPTION
**Pull request by mgold1234**
related to: THEEDGE-2337

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by ldjebran** [comment]
seems ok, will see tomorrow about merging

**Comment by AaronH88** [comment]
All these changes look OK.

I can see that the `imageset` struct is in `models/images` 

I think that `Account` should be removed from this model in this PR. Let me know what you think?

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Pull request merged**
