### PR TITLE
update: Fix playbook template.

### PR DESCRIPTION
**Pull request by ldjebran**
## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
Templates must be signed before merge

**Comment by AaronH88** [comment]
/lgtm 

Let me know when signed so I can approve

**Comment by ldjebran** [comment]
Contacted @rexwhite for the playbook template signature.

**Comment by rexwhite** [comment]
I signed the template but I don't have permission to push to @ldjebran's fork and I have no idea how to add a commit from a different fork to this PR.  What would you like me to do with the signed file?

**Comment by ldjebran** [comment]
many thanks @rexwhite 
(The playbook was sent to me offline, and created a new commit)

**Review by de1987 — APPROVED** [review]

**Pull request merged**
