### PR TITLE
Found small spell correction

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
48699462-f02d-4235-b0e8-3bb790f6c095
9f36e2a0-feec-4399-9dbf-b1f035acd991

**Review by AaronH88 — APPROVED** [review]

**Review by loadtheaccumulator — APPROVED** [review]

**Comment by thom-at-redhat** [comment]
@Mergifyio refresh

**Pull request merged**
