### PR TITLE
fixes(HMS-4620): add RHEL 8.10

### PR DESCRIPTION
**Pull request by lzap**
SSIA

@loadtheaccumulator can you guide me what else I need to do in order to add RHEL 8.10?

### CODE REVIEW

**Review by loadtheaccumulator — CHANGES_REQUESTED** [review]
You have two of the three changes. Just need to add it to the DistributionRefs map at Line 66

**Review by loadtheaccumulator — DISMISSED** [review]
lgtm

**Comment by loadtheaccumulator** [comment]
Ugh. @lzap Test failing, and not sure why 81 hasn't failed before now.

```
 --- FAIL: TestValidateRepo (0.00s)
    --- FAIL: TestValidateRepo/validate_major#01 (0.00s)
        repo_config_test.go:27: "81" not found: ""
FAIL
FAIL	github.com/redhatinsights/edge-api/config	0.006s
```

**Comment by loadtheaccumulator** [comment]
I see the line in the test. It should only be failing in the test, and not elsewhere in the code.
It should get passed through, although, I am not sure what value IB is expecting.

**Comment by lzap** [comment]
Right, it appears that image builder has now two forms for distros: `rhel-89` and `rhel-8.10`. I have rewritten the test to use regular expression to capture both formats.

What is next? Do we need to add this to UI?

**Review by loadtheaccumulator — APPROVED** [review]
lgtm

**Comment by loadtheaccumulator** [comment]
UI is next. I can also use 8.10 for my next test this morning via the API

**Pull request merged**
