### PR TITLE
images: replace GetRepositoryByUUID with GetRepositoryByURL.

### PR DESCRIPTION
**Pull request by ldjebran**
# Description
In the context of content-sources images repository take into resolve content-sources existence by URL instead of UUID, as the UUID may change. 

FIXES: THEEDGE-3287

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by de1987 — APPROVED** [review]

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by ldjebran** [comment]
automatic merge is not possible for maydev, as having two approval merge manually

**Pull request merged**
