### PR TITLE
Update cloud image to konflux

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Update deploy image to konflux image

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
This is a follow up PR for Konflux this should go in later after this is in - https://github.com/RedHatInsights/edge-api/pull/2715

**Comment by mshriver** [comment]
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGp2Yml3NXVqazZ6cWF3andrM3N6Y2s3YncyeWNra3Vkc3Bpajd1eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/87xihBthJ1DkA/giphy.gif

**Review by lzap — APPROVED** [review]

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
Edge-api seems broken right now.

**Review by lzap — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
:tada:

**Pull request merged**
