### PR TITLE
add checksum to ISO image

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

### CODE REVIEW

**Review by biancarosa — COMMENTED** [review]
LGTM so  far, bur at which point on the code are we filling this field with the actual checksum?

**Comment by loadtheaccumulator** [comment]
services/images.go lines 526-528

**Comment by loadtheaccumulator** [comment]
> LGTM so far, bur at which point on the code are we filling this field with the actual checksum?

services/images.go lines 526-528

**Review by biancarosa — APPROVED** [review]
Sorry I missed it! It's looking great :)

**Pull request merged**
