### PR TITLE
utility: change stale interrupted time from 48 to 6 hours

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Change stale interrupted build time from 48 hours to 6 hours.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5659b05e-2712-4594-a434-4a2d3ff50b3b
8740b0bf-92af-4cc8-9f01-d99b0a6addc8

**Review by thom-at-redhat — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
2ceef792-5478-4ff0-ac18-0f07a11fe074
c1faaf22-bfb7-446d-b20f-016b14239a53

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
5425ea7e-721e-4cd3-96c5-12d819af3090
89cd80d6-cfd3-4972-bffd-bd4eaa043165

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
42b3c4da-544e-4a1d-8565-0cafa3922d4e
8a2bc203-f5c7-4f7c-a5d9-887f22dabe28

**Pull request merged**
