### PR TITLE
Add example and description to device_api

### PR DESCRIPTION
**Pull request by mgold1234**
# Description
related to story -https://issues.redhat.com/browse/THEEDGE-3384 

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update
- [ ] Tests update
- [x] Refactor

### CODE REVIEW

**Comment by loadtheaccumulator** [comment]
Just realized we're reviewing the same changes twice. Consider combining with the other PR, or we can wait until it is merged before looking at this one.

**Comment by loadtheaccumulator** [comment]
@mgold1234 you should be able to re-push the changes to this PR now.

**Comment by mgold1234** [comment]
@loadtheaccumulator will do, thank you

**Comment by mgold1234** [comment]
there is a lot of conflict here I am closing this one, and open new one

**Comment by mgold1234** [comment]
https://github.com/RedHatInsights/edge-api/pull/2151/

**Pull request closed without merging**
