### PR TITLE
Add Og to CODEOWNERS

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

Allow Og to be the BOSS that he is!

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
https://giphy.com/gifs/but-qUIm5wu6LAAog

**Review by de1987 — APPROVED** [review]

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by thom-at-redhat** [comment]
I had to allow edits and access by maintainers

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Pull request merged**
