### PR TITLE
Theedge 2178 update template

### PR DESCRIPTION
**Pull request by acosferreira**
# Description

Change template to run the rebase once the refs changes (update from 8.6 to 9.0).
If is a minor update should continue running the upgrade

Fixes # ([issue](https://issues.redhat.com/browse/THEEDGE-2178))

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-e6e61210-8124-4329-b6a9-b30458d3d99e

**Comment by omaciel** [comment]
@acosferreira just a reminder that:
* The template will have to be resigned
* The test template will have to be updated with the same signature in order to pass unit tests

**Review by maxamillion — COMMENTED** [review]
LGTM :+1:

**Comment by acosferreira** [comment]
image
Tested the template manually and worked as expected with the conditions

**Comment by acosferreira** [comment]
image

**Comment by acosferreira** [comment]
only merge it when we get the signature.

**Comment by acosferreira** [comment]
@rexwhite can you help up on this playbook changes?

**Comment by rexwhite** [comment]
@acosferreira Sure thing!  Do you want all three playbooks signed?

**Comment by acosferreira** [comment]
@rexwhite  I believe we need only this [templates/template_playbook_dispatcher_ostree_upgrade_payload.yml]
The others are for unit tests.
Thanks!

**Comment by rexwhite** [comment]
I signed the playbook and submitted a separate PR (https://github.com/RedHatInsights/edge-api/pull/1258) because I have no idea how to add to this one from my own fork.  You can either cherry-pick the file out of the other PR or just merge them both (or let me know how the heck to contribute to this PR from a different fork)

**Comment by acosferreira** [comment]
Closing due to get the signature and rebased on 
https://github.com/RedHatInsights/edge-api/pull/1258/

**Pull request closed without merging**
