### PR TITLE
Increase test coverage on GetImageThirdPartyRepos

### PR DESCRIPTION
**Pull request by adeliaferreira**
# Description
This PR will add new test case to cover cases on GetImageThirdPartyRepos inside pkg/clients/imagebuilder/client.go
FIXES:  THEEDGE-3057

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

### CODE REVIEW

**Comment by ldjebran** [comment]
test looks good, please add a positive unittest  calling GetImageThirdPartyRepos.

**Review by ldjebran — COMMENTED** [review]
test looks good, please add a positive unittest calling GetImageThirdPartyRepos.

**Comment by adeliaferreira** [comment]
I'll add this test in my next pr, could be ?

**Comment by AaronH88** [comment]
I agree with Djebran, looking great so far, can we please add a positive test, 
We can add it to this PR as so far its only 33 lines changed :smile:

**Comment by adeliaferreira** [comment]
@AaronH88 @ldjebran new test case suggested was added in the new version for this PR. Thanks for the suggestion, new coverage details are available on this link: https://app.codecov.io/gh/RedHatInsights/edge-api/blob/test-third-party-repo-not-retrieve/pkg/clients/imagebuilder/client.go

**Review by AaronH88 — APPROVED** [review]
/lgtm

If you feel like it, feel free to refactor any test you see for code reuse. But this looks great and OK to merge :smile:

**Review by ldjebran — APPROVED** [review]
looks great , Thanks Tay

**Pull request merged**
