### PR TITLE
add validation on rhc to avoid fire update for disconnected device

### PR DESCRIPTION
**Pull request by acosferreira**
# Description

Avoid fire an update to devices that doesn't present the RHC_CLIENT_ID, once they will fail due unavailable connectivity.

Fixes # ([issue](https://issues.redhat.com/browse/THEEDGE-2094))

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes
- [X] I run `make lint` to prints out coding style mistakes and fix them

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3401d0ea-8c46-45be-9493-7be2db66f473
fb795d30-11fd-402f-96d9-e95360987e63

**Review by ldjebran — APPROVED** [review]
LGMT

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Comment by thom-at-redhat** [comment]
@mergifyio requeue

**Pull request merged**
