### PR TITLE
Fix linter to highlight issues with body close

### PR DESCRIPTION
**Pull request by psav**
# Description

This should enable the linting of body close

### CODE REVIEW

**Review by ldjebran — APPROVED** [review]

**Comment by ldjebran** [comment]
@tomershinhar @lahavyuv86 @de1987 thanks to investigate , this PR does not make changes that may affect the tests in automation to fail, but we have 6 tests failing for the 3 rd time (about custom repos).

**Review by omaciel — APPROVED** [review]
/lgtm

**Pull request merged**
