### PR TITLE
Refactoring Edge configuration module.

### PR DESCRIPTION
**Pull request by omaciel**
# Description

Refactoring `config/config.go` to hopefully make it easier to test it.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by mgold1234** [comment]
retest

**Review by ldjebran — APPROVED** [review]
/lgtm

**Comment by ldjebran** [comment]
remove do not merge as automation is ok now

**Review by acosferreira — APPROVED** [review]
/lgtm

**Pull request merged**
