### PR TITLE
linter: fixes linter revive

### PR DESCRIPTION
**Pull request by ldjebran**
# Description
The linter is complaining on different problems 

see https://github.com/RedHatInsights/edge-api/actions/runs/7841552281/job/21401671419?pr=2410 

skip linter revive check on base code linter problems, on some places refactor, on tests disable check on file. on base code that seems to be removed in the future , skip the files for revive check.

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor
- [X] Linter fixes

### CODE REVIEW

**Comment by omaciel** [comment]
My only concern is that we might be creating more code smells for the future. I see that there is a lot of tiny changes required and most of them with no obvious benefit other than silencing the linter, but I can't help but wonder what potential security issues not fixing these issues would cause for us?

**Comment by ldjebran** [comment]
The intention of this PR is to free our automation for the moment for this error, so that we can merge more important PRs 
 I will recap the changes I made , 
on base code: 
- refactored where no too much code refactoring involved   
- skipped where only where name changing is involved 
- skipped all files , on migration scripts that are going to be deleted 

on unit test skip the revice check on files as does not affect the app functionality.

@omaciel I agree with you that we should fix this in all our code.

**Review by omaciel — APPROVED** [review]
/lgtm

Trust me, I understood your intentions and I know that you chose the least of two possible evils 😁 I appreciate that you agree that we should fix things in our code and I hope that we can do it sooner than later so we don't add to our code debt.

**Review by adeliaferreira — APPROVED** [review]
Lgtm

**Pull request merged**
