### PR TITLE
resetting logging to debug for inventory and dispatcher

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Changing back to debug for inventory and dispatcher event logging.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by acosferreira — COMMENTED** [review]
lgtm

**Review by AaronH88 — APPROVED** [review]
lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
31b386e3-10da-4d37-8bc4-6214169f9234
60e5824f-12f6-4af2-8a75-a443df346ec8

**Review by thom-at-redhat — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1bdf33c8-e4e9-4892-a8d0-8afc461f1cef
3fbb1779-94e4-45e3-8bb2-e5751c194e45

**Pull request merged**
