### PR TITLE
Signing updated playbooks.

### PR DESCRIPTION
**Pull request by rexwhite**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-ef1ab9a8-32aa-4339-89b2-69475faeba3c

**Comment by omaciel** [comment]
Make test template changes as per slack chat and tests should pass.

**Comment by omaciel** [comment]
Two IQE tests have failed and need to get fixed.

**Review by ldjebran — APPROVED** [review]
LGMT

**Pull request merged**
