### PR TITLE
Make mergify rule names unique and use shared key

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

1) Correct typo with duplicate rule names in mergify
2) Change mergify criteria to use shared keys

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by ldjebran — APPROVED** [review]

**Comment by omaciel** [comment]
@mergify refresh

**Review by omaciel — APPROVED** [review]

**Comment by omaciel** [comment]
@mergify requeue

**Comment by omaciel** [comment]
@mergify unqueue

**Comment by omaciel** [comment]
@mergify queue

**Comment by omaciel** [comment]
@mergify queue default

**Pull request merged**
