### PR TITLE
parity: add feature flag config for content sources

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
# Description
Add a feature flag for Parity work related to custom repositories

FIXES: THEEDGE-3085

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by ldjebran — DISMISSED** [review]
lgtm

**Comment by omaciel** [comment]
```
10:46:27 Error: error creating container storage: the container name "edge-pr-check-1910" is already in use by "efdafd2289f475ab024e496bf9dd1af6268b97dec4e8d2dcf865813203760f2e". You have to remove that container to be able to reuse that name.: that name is already in use
```

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by ldjebran — APPROVED** [review]

**Pull request merged**
