### PR TITLE
Add validation to package names when creating/updating image.

### PR DESCRIPTION
**Pull request by mgold1234**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
a3d3e7e8-42f5-4f74-877e-be7b98aefaba
e0e97923-d6f5-4abb-b223-acd4e6e5e608

**Comment by ldjebran** [comment]
This PR was restored from PR https://github.com/RedHatInsights/edge-api/pull/1079

**Review by ldjebran — APPROVED** [review]
LGMT

**Comment by ldjebran** [comment]
@Mergifyio refresh

**Comment by ldjebran** [comment]
@Mergifyio requeue

**Comment by ldjebran** [comment]
@Mergifyio rebase

**Comment by ldjebran** [comment]
all tests passed including integration ones https://ci.int.devshift.net/job/RedHatInsights-edge-api-pr-check/1968/consoleFull

merge manually .

**Pull request merged**
