### PR TITLE
FIX- sorting image-sets by status returns 400

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
# Description

We've disabled sorting using status for image-sets endpoint. But we forgot to make changes to the response when status is used as a sorting parameter. 

Currently the endpoint **image-sets?sort_by=status** responds with 400 instead, it should respond with something like this 

`[
  {
    "Key": "sort_by",
    "Reason": "status is not a valid sort_by. Sort-by must created_at or updated_at or name"
  }
]`
Fixes # [THEEDGE-1616]

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes
- [x] I run `make lint` to prints out coding style mistakes and fix them

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
0f05fb3a-65d0-4a5b-9d83-26d3401b998b
75dadc91-b72c-4343-8952-555046f9ce26

**Review by mgold1234 — COMMENTED** [review]
I ran 'TestSearchParams' function that use  sortOption variable in validateFilterParams function and this test failed on : 
=== RUN   TestSearchParams
    imagesets_test.go:132: in "bad sort_by": was expected to have {sort_by test is not a valid sort_by. Sort-by must created_at or updated_at or name or status} but not found in [{sort_by test is not a valid sort_by. Sort-by must created_at or updated_at or name}]
    imagesets_test.go:132: in "bad sort_by and status": was expected to have {sort_by host is not a valid sort_by. Sort-by must created_at or updated_at or name or status} but not found in [{status ONHOLD is not a valid status. Status must be CREATED or BUILDING or ERROR or SUCCESS} {sort_by host is not a valid sort_by. Sort-by must created_at or updated_at or name}]
--- FAIL: TestSearchParams (6.22s)

**Comment by Saurabh-Thakre** [comment]
> I ran 'TestSearchParams' function that use sortOption variable in validateFilterParams function and this test failed on : === RUN TestSearchParams imagesets_test.go:132: in "bad sort_by": was expected to have {sort_by test is not a valid sort_by. Sort-by must created_at or updated_at or name or status} but not found in [{sort_by test is not a valid sort_by. Sort-by must created_at or updated_at or name}] imagesets_test.go:132: in "bad sort_by and status": was expected to have {sort_by host is not a valid sort_by. Sort-by must created_at or updated_at or name or status} but not found in [{status ONHOLD is not a valid status. Status must be CREATED or BUILDING or ERROR or SUCCESS} {sort_by host is not a valid sort_by. Sort-by must created_at or updated_at or name}] --- FAIL: TestSearchParams (6.22s)

Hey, where did you get that error? I didn't get it locally, it'd be great if you show it to me

**Review by ldjebran — CHANGES_REQUESTED** [review]
seems removing the status only is not enough, I am having the unit-tests locally failing.

**Comment by ldjebran** [comment]
This is failing locally because of unit-tests not updated , the validation errors messages needs to be updated , remove the status from the message.

**Comment by ldjebran** [comment]
@Mergifyio rebase

**Comment by ldjebran** [comment]
@Saurabh-Thakre you will need to rebase your local branch.

**Comment by Saurabh-Thakre** [comment]
I'm putting this on a hold for a while.

**Comment by ldjebran** [comment]
PR closed and  restored in https://github.com/RedHatInsights/edge-api/pull/1168

**Pull request closed without merging**
