### PR TITLE
Fix else statement

### PR DESCRIPTION
**Pull request by biancarosa**
# Description

Follow-up on #454 as I introduced a bug.

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by omaciel** [comment]
@biancarosa can haz test?

**Comment by biancarosa** [comment]
@omaciel absolutely, that was my bad :) updated

**Comment by omaciel** [comment]
Thank you @biancarosa  :)

**Review by acosferreira — APPROVED** [review]
LGTM

**Pull request merged**
