### PR TITLE
image-sets: fixes undocumented delete methods with documented one.

### PR DESCRIPTION
**Pull request by ldjebran**
# Description
- Update the image-set delete with documented ways to do so (see https://gorm.io/docs/delete.html)
- update all gorm dependencies to latest versions. 
FIXES: THEEDGE-3414

The unitests are in place to check the delete is working.

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by loadtheaccumulator — APPROVED** [review]
lgtm

**Comment by mgold1234** [comment]
do the changes in go.mod and go.sum related o that pr?

**Comment by ldjebran** [comment]
> do the changes in go.mod and go.sum related o that pr?

Yes it's related as described in the description

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
