### PR TITLE
removed reserved-usernames endpoint and constants file

### PR DESCRIPTION
**Pull request by resoluteCoder**
Removed the reserved username endpoint since it is being stored on the frontend and removed the associated constants file

### CODE REVIEW

**Review by acosferreira — APPROVED** [review]
/LGTM

**Review by biancarosa — APPROVED** [review]

**Comment by biancarosa** [comment]
D'you have the right permissions to merge this @resoluteCoder ?

**Comment by resoluteCoder** [comment]
I think so? The green button is enabled and calling to me

**Pull request merged**
