### PR TITLE
Fix SetErrorStatusOnImage SIGSEGV

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

Fix SIGSEGV in SetErrorStatusOnImage.  "tx.Error.Error()" was accidentally used instead of "err.Error()"

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Review by loadtheaccumulator — COMMENTED** [review]
Do we even need the if err block here? It doesn't update the Database and is logging an error from a different call. I'm thinking that err should be logged where it happens.

**Review by loadtheaccumulator — APPROVED** [review]
lgtm

Needs to be refactored out to the calling code.

**Comment by thom-at-redhat** [comment]
@Mergifyio refresh

**Pull request merged**
