### PR TITLE
FIX : "limit" returns the count as total number of image-sets 

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
# Description

"limit" list-all-image-sets endpoint returns the total number of image-sets in count and not the count of the returned payload

Fixes #THEEDGE-2223

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by acosferreira — CHANGES_REQUESTED** [review]
when you look to this result, if there is no limit value, the result will be always 30, and this will breadk the ui pagination
you need to add a fix to the count, to when receive the parameter of limit, the count also consider this value and return the correct amount

**Comment by AaronH88** [comment]
Waiting for Ana's comment to be addressed :smile:

**Review by ldjebran — COMMENTED** [review]
I commented in the original issue , but also comment here.
This this is not a bug , this how pagination and filtering works, we return the count of all entities affected only and only by the the filter.    
Otherwise the pagination will not work. 

Think we should close this PR.

and the issue as not a bug.

**Comment by Saurabh-Thakre** [comment]
@ldjebran @AaronH88 yes, I;m working on it to make sure we have a condition where if the user passes a limit then we will respect that limit and show it in count.

**Comment by Saurabh-Thakre** [comment]
closing the PR, the bug has been declared as not a bug after discussion

**Pull request closed without merging**
