### PR TITLE
rename column. Add new fields to device

### PR DESCRIPTION
**Pull request by acosferreira**
# Description

Add new fields to device table to accommodate new values for device groups 

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Review by biancarosa — COMMENTED** [review]
I think we're only missing one update to the CurrentHash when we finish the update, that is, on the Kafka consumer that we already have that reads from playbook dispatcher's messages

**Review by biancarosa — APPROVED** [review]
LGTM

**Comment by Avielyo10** [comment]
@acosferreira needs rebase

**Pull request merged**
