### PR TITLE
content-sources: Apply the same rules as for content-sources repos.

### PR DESCRIPTION
**Pull request by ldjebran**
# Description

As the edge and content-sources services have different rules, before migration edge-management needs to comply with content-sources rules:
- Create a validator that verifies that the url does not exist before creating a new one.
- When creating/updating repos modify the url to terminate with slash "/"

FIXES: THEEDGE-3261

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by acosferreira — APPROVED** [review]
lgtm

**Comment by ldjebran** [comment]
@acosferreira Added ThirdPartyRepo route errors when creating and updating with unittests @please revisit

**Comment by ldjebran** [comment]
The automation tests are failing as need update as per task [THEEDGE-3264] will write here when fixed.

**Review by loadtheaccumulator — APPROVED** [review]

**Pull request merged**
