### PR TITLE
BUGFIX- sorting image-sets by status returns 400

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
# Description

We've disabled sorting using status for image-sets endpoint. But we forgot to make changes to the response when the status is used as a sorting parameter. 

Currently the endpoint **image-sets?sort_by=status** responds with 400 instead, it should respond with something like this 

`[
  {
    "Key": "sort_by",
    "Reason": "status is not a valid sort_by. Sort-by must created_at or updated_at or name"
  }
]`
Fixes # [THEEDGE-1616]

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes
- [x] I run `make lint` to prints out coding style mistakes and fix them

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1cacf976-26aa-4fad-a7c2-1997544d9310

**Comment by AaronH88** [comment]
Great start, one change requested

**Comment by Saurabh-Thakre** [comment]
> Great start, one change requested

I don't see any change you requested :(

**Comment by ldjebran** [comment]
PR restored from closed  https://github.com/RedHatInsights/edge-api/pull/1095

**Comment by AaronH88** [comment]
> > Great start, one change requested
> 
> I don't see any change you requested :(

It is in my comment on the `pkg/routes/imagesets.go` file

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Comment by Saurabh-Thakre** [comment]
@mergifyio unqueue

**Comment by Saurabh-Thakre** [comment]
@mergifyio refresh

**Comment by Saurabh-Thakre** [comment]
@mergifyio requeue

**Pull request closed without merging**
