### PR TITLE
Fix S3Proxy

### PR DESCRIPTION
**Pull request by maxamillion**
* Re-Add NewS3Proxy
* Fix prefix parsing to include the update number
* Add debug output

Signed-off-by: Adam Miller <admiller@redhat.com>

### CODE REVIEW

**Review by biancarosa — APPROVED** [review]
LGTM. Only check not passing is relative to something that's already on the master branch, I  fixed on my PR already, so I don't think it's worthy to hold this on

**Comment by maxamillion** [comment]
Yeah, don't merge this yet. I just realized this breaks something. I'll deal with that later.

**Comment by maxamillion** [comment]
Closing for now, I'll re-open when I fix it but I'm going on PTO so it'll be a little bit.

**Comment by maxamillion** [comment]
Never mind, the failure I ran into turns out to be disjoint from this.

**Pull request merged**
