### PR TITLE
add continue after static delta

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
* add StaticDeltaStatusError to switch
* send all errors to errChan in select

# Description
Add additional handling for error'd static delta 

FIXES: 

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

### CODE REVIEW

**Review by ldjebran — APPROVED** [review]
lgtm

**Comment by loadtheaccumulator** [comment]
@mergifyio rebase

**Comment by de1987** [comment]
@mergifyio rebase

**Pull request merged**
