### PR TITLE
Increased test coverage for models.Images package to 100%

### PR DESCRIPTION
**Pull request by omaciel**
* Refactored existing tests to call BeforeCreate methods implicitly for images and imagesets
* Added tests to check for presence of orgId for images and imageSets
* Added tests for package list without a distribution

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
From 95.2% to 100%

**Review by acosferreira — COMMENTED** [review]
lgtm

**Review by acosferreira — APPROVED** [review]

**Comment by mgold1234** [comment]
need to fix lint failure  level=error msg="Running error: context loading failed: no go files to analyze

**Review by ldjebran — APPROVED** [review]
lgtm, but seems the linter complaining

**Comment by omaciel** [comment]
Thing is I can't tell what the issue is that lint is reporting. Any ideas?

**Pull request merged**
