### PR TITLE
validate env based on clowder config

### PR DESCRIPTION
**Pull request by acosferreira**
# Description
change gpg set based on clowder env

FIXES:  THEEDGE-3051

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by omaciel — COMMENTED** [review]
I feel that we should make gpgcheck to be true regardless of which environment we're running, unless there's a legitimate reason for disabling it on stage that I'm not aware of?

**Review by mgold1234 — COMMENTED** [review]
Can you please explain the purpose of this change?

**Comment by acosferreira** [comment]
@mgold1234 you can check the ticket related

**Comment by acosferreira** [comment]
@omaciel i'm looking into the params on image creation/update to identify the reason of not being always true.

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by loadtheaccumulator — APPROVED** [review]
lgtm

**Review by thom-at-redhat — APPROVED** [review]

**Pull request merged**
