### PR TITLE
image-builder: pass installer user and ssh-key to image-builder

### PR DESCRIPTION
**Pull request by ldjebran**
# Description
Pass installer user and ssh-key to image-builder when creating ISO artifact. 

FIXES: https://issues.redhat.com/browse/THEEDGE-3713

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by de1987 — APPROVED** [review]

**Comment by de1987** [comment]
@mergifyio rebase

**Pull request merged**
