### PR TITLE
Enables development with postgresql

### PR DESCRIPTION
**Pull request by biancarosa**
add this to env:

DATABASE=pgsql
PGSQL_USER=user
PGSQL_PASSWORD=pass
PGSQL_HOSTNAME=127.0.0.1
PGSQL_PORT=5432
PGSQL_DATABASE=db

run your container:

podman run -d --name postgresql_database -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=db -p 5432:5432 rhel8/postgresql-10

have fun

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
Can this info be added to the README?

```
add this to env:

DATABASE=pgsql
PGSQL_USER=user
PGSQL_PASSWORD=pass
PGSQL_HOSTNAME=127.0.0.1
PGSQL_PORT=5432
PGSQL_DATABASE=db

run your container:

podman run -d --name postgresql_database -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=db -p 5432:5432 rhel8/postgresql-10

have fun
```

**Comment by biancarosa** [comment]
yes, on it @maxamillion

**Review by acosferreira — APPROVED** [review]

**Comment by biancarosa** [comment]
@maxamillion let me know if the readme works like that!

**Comment by maxamillion** [comment]
@biancarosa looks great, thank you!

**Pull request merged**
