### PR TITLE
linter: Fixes ImageDetails lint unsed at images modules.

### PR DESCRIPTION
**Pull request by ldjebran**
# Description
golangci-lint does not parse well this block, it says for example Image not used, but it's used later in the code.

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by tomershinhar — APPROVED** [review]
LGTM

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
