### PR TITLE
images: fixes route images module and create/update validation errors.

### PR DESCRIPTION
**Pull request by ldjebran**
What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by acosferreira — APPROVED** [review]
lgtm

**Review by mgold1234 — COMMENTED** [review]
/lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
cb9a9a21-2829-4e96-a523-8ed6cd8e6fa5

**Comment by AaronH88** [comment]
QE tests are failing, is this because the returned error messages have changed?

**Pull request merged**
