### PR TITLE
add value to identify when a device its being updated

### PR DESCRIPTION
**Pull request by acosferreira**
# Description

add new field to get status of device when update is running

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
046bf1c2-017f-418a-b703-d876079b041a
67ffbca1-1f32-48e5-907e-91d4da74469a

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1d94875d-ac9d-4613-9453-6c1e9326aa31
c42e4abc-6e4b-4858-ac0f-1cccaa7f623c

**Review by thom-at-redhat — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1cdee175-0416-4a39-930c-127ff66362fb
b4e076d7-1b4a-4721-a9f2-1a5c1b0f8142

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
0a3e4463-d9be-41b8-9ed7-59ed06fb11de
4db69959-914b-4607-9f0d-943b5375a9dd

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
6bc91633-ab04-4f23-bddb-97931bb75b5f
b74020c7-1470-445e-8399-9990ebd154ba

**Pull request merged**
