### PR TITLE
fix insights collect data after reboot

### PR DESCRIPTION
**Pull request by acosferreira**
# Description
#RHE92 related
After ran an update the insights-client is not uploading the correct data on reboot.
the log report an error:
```
2023-06-26 21:45:12,593  NETWORK insights.client.connection HTTP Response Text: {"request_id":"94edde8818424f3d8b6b0243c7bcbd84","upload":{}}
2023-06-26 21:45:12,593    DEBUG insights.client.connection Request ID: 94edde8818424f3d8b6b0243c7bcbd84, 94edde8818424f3d8b6b0243c7bcbd84
2023-06-26 21:45:12,594    DEBUG insights.client.connection {"request_id":"94edde8818424f3d8b6b0243c7bcbd84","upload":}}
2023-06-26 21:45:12,594    DEBUG insights.client.connection Upload duration: 0:00:01.679358
2023-06-26 21:45:12,595    ERROR insights.client.phase.v1 [Errno 13] Permission denied: '/etc/insights-client/.lastupload'
```

this fix will correct the permission during the image creation and avoid the continue and get our inventory information updated.

FIXES:  THEEDGE-3335 

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Comment by acosferreira** [comment]
`[fleetmgmt@localhost ~]$ sudo tail -f  /var/log/insights-client/insights-client.log
2023-06-27 17:07:01,527    DEBUG insights.client.connection Uploading /var/tmp/insights-client/insights-archive-bd_7er48/insights-localhost-20230627210544.tar.gz to https://cert.cloud.stage.redhat.com/api/ingress/v1/upload
2023-06-27 17:07:01,527  NETWORK insights.client.connection POST https://cert.cloud.stage.redhat.com/api/ingress/v1/upload
2023-06-27 17:07:01,941  NETWORK insights.client.connection HTTP Status: 202 Accepted
2023-06-27 17:07:01,941  NETWORK insights.client.connection HTTP Response Text: {"request_id":"44dec13f4fca4b4198012dca58591ace","upload":{"account_number":"6089719","org_id":"11789772"}}
2023-06-27 17:07:01,941    DEBUG insights.client.connection Request ID: 44dec13f4fca4b4198012dca58591ace, 44dec13f4fca4b4198012dca58591ace
2023-06-27 17:07:01,941    DEBUG insights.client.connection {"request_id":"44dec13f4fca4b4198012dca58591ace","upload":{"account_number":"6089719","org_id":"11789772"}}
2023-06-27 17:07:01,941    DEBUG insights.client.connection Upload duration: 0:00:00.410841
2023-06-27 17:07:01,943     INFO insights.client.client Successfully uploaded report for localhost.localdomain.
2023-06-27 17:07:01,944    DEBUG insights.client Cached branch_info file does not exist.
2023-06-27 17:07:01,944    DEBUG insights.client.archive Deleting: /var/tmp/insights-client/insights-archive-brae_lp0
`

**Review by loadtheaccumulator — APPROVED** [review]
lgtm

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
