### PR TITLE
refactor packageDiff sturcture in case there is no changes when comapring packages

### PR DESCRIPTION
**Pull request by mgold1234**
related to bug -[THEEDGE-2578](https://issues.redhat.com/browse/THEEDGE-2578) in case we dont have any changes when comparing packages, I want to see 0 instead of null
 related to bug of pacakageDiff

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
Can you make sure that we have a test for this? I'm not in front of the computer right now and I think this should be an easy test to add if we don't currently have one.

**Comment by mgold1234** [comment]
@omaciel I added some unit test for that, thank you for mention it

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by de1987 — APPROVED** [review]

**Pull request merged**
