### PR TITLE
Updating IQE trigger template for edge backend

### PR DESCRIPTION
**Pull request by adarshdubey-star**
The test runs are not getting reported to ibutsu which causes issues in debugging , as the template is quite old with the set params.

### CODE REVIEW

**Review by akhil-jha — APPROVED** [review]

**Review by ezr-ondrej — APPROVED** [review]
Akhil thinks it's fine, that's good enough for me. If you need a proper review, let me know, but I'm ok to get it in and see if it works :)
For proper review, I'd need to figure out how these templates work :stuck_out_tongue:

**Comment by adarshdubey-star** [comment]
The deployment for eph env is failing for some reason , I see similar failure in the gitlab iqe-edge pipeline as well

**Pull request merged**
