### PR TITLE
Fix key for glitchtip-dsn Vault secret

### PR DESCRIPTION
**Pull request by tpapaioa**
# Description

Vault secret for glitchtip-dsn was using the wrong `key` value, causing the edge-api-service pod to fail to start.

FIXES: 

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Review by AaronH88 — COMMENTED** [review]
looking for an example from another team :smile:

**Comment by dehort** [comment]
On line [24](https://github.com/RedHatInsights/edge-api/pull/1897/files#diff-50b41779d45e37968dc1bef161feebad3447f6c3cf72cfee62db774ecd5dfa4dR24), try this:

`
    dsn: ${GLITCHTIP_DSN}
`

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Pull request merged**
