### PR TITLE
Added check for ephemeral env, modified the unleash token to include …

### PR DESCRIPTION
**Pull request by AaronH88**
…bearer.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes
- [X] I run `make lint` to prints out coding style mistakes and fix them

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
13312552-f300-434c-9fcb-959d9040d29f
7b200ec4-292f-478a-93e7-72182c03904e

**Comment by omaciel** [comment]
FWIW we still have the issue with custom repositories feature flag check (`/api/edge/v1/thirdpartyrepo`) returning a 501:

```json
{"Code":"FEATURE_NOT_AVAILABLE","Status":501,"Title":"Feature not available"}
```

**Comment by omaciel** [comment]
I just learned from @AaronH88  that when running edge-api locally, you do not set the UNLEASHE environment variables. Moving on

**Comment by AaronH88** [comment]
getting a second set of eyes on this and confirming it works before pushing :)

**Pull request merged**
