### PR TITLE
fix sudoers group name

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
* imagebuilder/client.go - swapped % for @ in group name

# Description
Swap % for @ in group name per sudoers format

FIXES: THEEDGE-3922

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Indeed, I saw the code but haven’t realized that:

https://linux.die.net/man/5/sudoers

**Comment by ezr-ondrej** [comment]
My bad! sorry for the bad review :face_exhaling:
The pipeline is broken due to ephemeral issues, I say this is pretty safe change (well in a sense it won't break the pipeline).

**Pull request merged**
