### PR TITLE
updates: fixes codebase for createUpdate async call.

### PR DESCRIPTION
**Pull request by ldjebran**
Make the go routine call internal to service, so that we can mock the service properly and test the call using expect function, the function go routine is detected in local dev env, but is flaky on GitHub.

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
79fdf31b-09a2-4a33-a00a-cb77931773ce
8bb15f9f-c725-46fb-aac9-13401998b9db

**Review by de1987 — APPROVED** [review]
lgtm

**Comment by AaronH88** [comment]
Now that CreateUpdate will be called Async, and we rely on our DB for indexing our updateids, should we lock the db call on line 120 in pkg/services/updates.go?
```
update.Status = models.UpdateStatusBuilding
lock()
db.DB.Save(&update)
unlock()
```

**Comment by AaronH88** [comment]
> > Now that CreateUpdate will be called Async, and we rely on our DB for indexing our updateids, should we lock the db calls on line 118 & 120 in pkg/services/updates.go?
> > ```
> > lock()
> > db.DB.Preload("DispatchRecords").Preload("Devices").Joins("Commit").Joins("Repo").Find(&update, id)
> > 	update.Status = models.UpdateStatusBuilding
> > db.DB.Save(&update)
> > unlock()
> > ```
> 
> CreateUpdate is not becaming async we are creating a new function that is named CreateUpdateAsync that call CreateUpdate in a go routine as original code is doing (the code always called CreateUpdate in a go routine). We need to investigate is the postgres driver connection used in gorm is thread safe (I am pretty sure it is ), but not in this PR, we are using go routine in many places in the code , so this worth a spike.

Happy with this reply, OK to merge

**Review by AaronH88 — APPROVED** [review]
lgtm

**Pull request merged**
