### PR TITLE
Snake_case on API Requests/Response

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**

### CODE REVIEW

**Review by loadtheaccumulator — COMMENTED** [review]
Are there corresponding changes in the front-end or other calls yet?

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by biancarosa** [comment]
Will be replaced by https://github.com/RedHatInsights/edge-api/pull/416

**Pull request closed without merging**
