### PR TITLE
devices: set/update device Name and LastSeen from inventory events.

### PR DESCRIPTION
**Pull request by ldjebran**
## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4939cd74-d844-4b61-ab87-b70d5516ebda
5da4687f-5c2d-46b6-b734-7cd92a6bd055

**Comment by omaciel** [comment]
@ldjebran any concerns about `db` migration when this is applied?

**Review by thom-at-redhat — APPROVED** [review]

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
10485091-0d05-4c24-97bb-4c3be6f36e30
df288426-eca2-403d-a67e-d7e37bb9de54

**Comment by ldjebran** [comment]
> @ldjebran any concerns about `db` migration when this is applied?
@omaciel no worries here , we are not changing any db model here , only the model of the message that we receive in the  inventory event.

**Pull request merged**
