### PR TITLE
thirdpartyrepo: Add end-point checkName.

### PR DESCRIPTION
**Pull request by ldjebran**
This allows UI to handle check name early. FIXES THEEDGE-2518 as back-end to allow FIXING of THEEDGE-2161.

Fixes # THEEDGE-2518 

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by omaciel — CHANGES_REQUESTED** [review]
Looks great! Should we ask a test for when the `orgId` is not found or invalid to cover the following code?

```go
if orgID == "" {
 		// logs and response handled by readOrgID
 		return
}
```

**Comment by ldjebran** [comment]
@omaciel  many thanks for the review, covered the ordID empty case.

**Review by omaciel — APPROVED** [review]
/lgtm

**Review by acosferreira — APPROVED** [review]
lgtm

**Pull request merged**
