### PR TITLE
build(deps): upgrade to Go 1.22

### PR DESCRIPTION
**Pull request by lzap**
SSIA

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
No idea what the linter wants, but we'll need to bump the Containerfile too

**Comment by ezr-ondrej** [comment]
I guess now just https://github.com/RedHatInsights/edge-api/blob/5fb007fdee45f5e5e7e07a474885967811eb391f/Dockerfile#L4 and we should be good? :)

**Comment by lzap** [comment]
Fixed.

**Comment by ezr-ondrej** [comment]
Eh :/ seee! I tried to resolve the merge conflict, but chose the wrong line, because the 1.22 tag just makes more sense to my brain xD

**Comment by lzap** [comment]
I agree, if you can make Konflux updater to use Go version instead, go for it.

Did you merged correctly tho? _This branch cannot be rebased due to conflicts_

**Comment by ezr-ondrej** [comment]
> I agree, if you can make Konflux updater to use Go version instead, go for it.
> 
> Did you merged correctly tho? _This branch cannot be rebased due to conflicts_

I tried resolve in GH for the first time and failed horribly

**Review by ezr-ondrej — APPROVED** [review]
I've resolved locally instead, if the pipeline succeeds, lets merge :+1:

**Pull request merged**
