### PR TITLE
fix ostree remote overwrite

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
# Description
Edit or create entries in the rhel-edge remote config file instead of overwriting the entire file.

FIXES: THEEDGE-3223

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Comment by loadtheaccumulator** [comment]
Additional error checking and tests after discussion in arch meeting.

**Comment by loadtheaccumulator** [comment]
Added additional checks and backup on change.
A couple of todos left for today before switching it from draft.

**Review by ldjebran — APPROVED** [review]
awesome idea to use python, I know that python3 is installed by default, but should we add it as a dependency (as a package when creating updating images ?)   what do you think?
PS: approval of this PR will require a re-approve, when when updating the signature

**Comment by loadtheaccumulator** [comment]
> awesome idea to use python, I know that python3 is installed by default, but should we add it as a dependency (as a package when creating updating images ?) what do you think?
> PS: approval of this PR will require a re-approve, when when updating the signature

Thanks! python3 is installed on Edge by default, so we are good there (for at least the foreseeable future).

**Comment by loadtheaccumulator** [comment]
@rexwhite Hi Rex, this one is ready for a signature. Please sign at will, and let me know if there's anything else I need to do. Cheers, Jonathan

**Comment by loadtheaccumulator** [comment]
Just a note. Rex's commit does not appear here because I essentially squashed things when I cleared up a tab issue after I copied the sigs to the tests.

**Review by ldjebran — APPROVED** [review]
lgtm

**Review by adeliaferreira — APPROVED** [review]
lgtm

**Review by acosferreira — APPROVED** [review]
lgtm

**Pull request merged**
