### PR TITLE
Start running smoke tests on pr_check

### PR DESCRIPTION
**Pull request by elyezer**

### CODE REVIEW

**Comment by elyezer** [comment]
I got the tests running but they are failing. It seems they are pointing to an environment that is not the one provisioned. I will investigate more but the changes will likely happen on test framework

**Comment by elyezer** [comment]
This is now running as expected and is ready for review.

**Review by biancarosa — APPROVED** [review]
This is awesome! How do we see the results of the smoke tests?

**Comment by elyezer** [comment]
@biancarosa if you expand the checks section and click on the details for the `ci.ext.devshift.net PR build` it should bring you to the right place. If you have trouble seeing it ping me.

**Comment by elyezer** [comment]
Just rebased. This is still passing and ready for anyone with write permission to merge it.

**Pull request merged**
