### PR TITLE
Remove PR approvals if new commits added

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

For mergify, remove approvals if new commits added

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

Ran yamllint and validated mergify configuration

### CODE REVIEW

**Comment by omaciel** [comment]
Makes sense to me.

/lgtm

**Comment by ldjebran** [comment]
so if I have made a PR , I received one approval, the second reviewer request changes , after that changes the PR will loose the first approval, the first reviewer will request changes to the changes I made , will make that changes ,then will loose the second approval, is this what we want to achieve ?
If this is the case I prefere, that this procedure must be done manually if necessary. 
In the scenario I described, if the second reviewer request to correct a typo in a comment or a variable name, we will loose the first approval.

**Review by de1987 — APPROVED** [review]

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Comment by thom-at-redhat** [comment]
@ldjebran Thank you for bringing this up.  For others who didn't attend the meeting this week, you and I discussed the issue with the team and we agreed to proceed with this PR.

**Review by omaciel — APPROVED** [review]
/lgtm

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Comment by thom-at-redhat** [comment]
@mergifyio queue

**Comment by thom-at-redhat** [comment]
@mergifyio queue default

**Pull request merged**
