### PR TITLE
Bugfix, /image/{ID} returning "null" for Repo

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
Repo returning "null" in /images/{ID} even if /images/{ID}/repo has the correct value.

**Before** 

> curl --request GET --url http://localhost:3000/api/edge/v1/images/1 | jq
{
  "ID": 1,
  "[...],
  "CommitID": 1,
  "Commit": {
    "ID": 1,
    "[...]     
    "Status": "SUCCESS",
    "RepoID": 1,
    "Repo": null
  },
  
  **After**
  
> curl --request GET --url http://localhost:3000/api/edge/v1/images/1 | jq
{
  "ID": 1,
  "[...],
  "CommitID": 1,
  "Commit": {
    "ID": 1,
    "[...]     
    "Status": "SUCCESS",
    "RepoID": 1,
    "Repo": {
      "ID": 1,
      "CreatedAt": "2021-11-22T14:45:14.412903899+05:30",
      "UpdatedAt": "2021-11-22T16:05:31.990486603+05:30",
      "DeletedAt": null,
      "RepoURL": "",
      "RepoStatus": "ERROR"
    }
  },

### CODE REVIEW

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Review by AaronH88 — APPROVED** [review]
Looks good to me

**Comment by Avielyo10** [comment]
@Mergifyio refresh

**Review by Avielyo10 — APPROVED** [review]
lgtm

**Pull request merged**
