### PR TITLE
device groups org id transition

### PR DESCRIPTION
**Pull request by lahavyuv86**
# Description

Updating db queries with new org_id for device groups service.
Jira ticket: https://issues.redhat.com/browse/THEEDGE-1982

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by ldjebran — APPROVED** [review]
LGMT

**Comment by ldjebran** [comment]
This PR is restored from closed PR https://github.com/RedHatInsights/edge-api/pull/1109

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
7f4a3f49-0036-4b91-a622-93fd939b01b7

**Pull request merged**
