### PR TITLE
added back status to imageSetFilters

### PR DESCRIPTION
**Pull request by tomershinhar**
# Description

added status back to imageSetFilters so that image-sets could be filtered by status

Fixes # (issue)
[THEEDGE-2343](https://issues.redhat.com/browse/THEEDGE-2343)
## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
Unittests?

**Comment by Saurabh-Thakre** [comment]
> Unittests?

We dont need unittest for this as we arleady did cover this

**Review by Saurabh-Thakre — APPROVED** [review]
lgtm, thanks Tomer for doing this

**Comment by omaciel** [comment]
@Saurabh-Thakre  @tomershinhar  actually we do not have unit tests for this change, which is not okay. Can we please add tests?

**Comment by tomershinhar** [comment]
@Saurabh-Thakre looking at the unit-tests it seems that we only have tests for sorting the image-sets and not for filtering them.

i will work on adding some unit tests for it

**Comment by tomershinhar** [comment]
@omaciel added some tests here https://github.com/RedHatInsights/edge-api/pull/1241

**Pull request merged**
