### PR TITLE
EDA cleanup unused device events

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
# Description
Remove unused message bus events and related feature flags

    Removed UpdateRepoRequested feature flag and related event producers for commit and installer completion
    Removed unused feature flag definitions

FIXES: HMS-4038

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
LGTM, tho what about `cmd/kafka/main.go` that goes last? :)

**Review by lzap — APPROVED** [review]
LGTM

**Comment by loadtheaccumulator** [comment]
> LGTM, tho what about `cmd/kafka/main.go` that goes last? :)

It is actually running the resume interrupted images process, so won't go with EDA.
There is also Kafka code used for Inventory create, update, delete events.

**Pull request merged**
