### PR TITLE
Fixed test coverage step name, Added Codecode and removed from Travis

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

1) Clarified Go test coverage vs. codecov
2) Added codecov as a Github Action
3) Removed codecov comment from Travis

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by mgold1234** [comment]
fail on lint-[2022-09-23T18:39:13.800Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`

**Review by acosferreira — APPROVED** [review]
lgtm

**Pull request merged**
