### PR TITLE
Add unittests for pkg/services/errors.go

### PR DESCRIPTION
**Pull request by omaciel**
# Description

Adds unittests for `pkg/services/errors.go` and updates all strings used for each error type to be a constant which should make it easier to maintain and write future tests.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
New tests uses `t.Run` for subtests:

```
go test -v -timeout 30s -run ^TestDeviceNotFoundError$ github.com/redhatinsights/edge-api/pkg/services
=== RUN   TestDeviceNotFoundError
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceNotFoundError
=== RUN   TestDeviceNotFoundError/Testing_for_*services.UpdateNotFoundError
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageNotFoundError
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageSetNotFoundError
=== RUN   TestDeviceNotFoundError/Testing_for_*services.AccountOrOrgIDNotSet
=== RUN   TestDeviceNotFoundError/Testing_for_*services.AccountNotSet
=== RUN   TestDeviceNotFoundError/Testing_for_*services.OrgIDNotSet
=== RUN   TestDeviceNotFoundError/Testing_for_*services.IDMustBeInteger
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryAlreadyExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryNameIsEmpty
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryURLIsEmpty
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryInfoIsInvalid
=== RUN   TestDeviceNotFoundError/Testing_for_*services.InvalidURLForCustomRepo
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryImagesExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageVersionAlreadyExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageNameAlreadyExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.PackageNameDoesNotExist
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageNameUndefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageSetUnDefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageUnDefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageSetAlreadyExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageNotInErrorState
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupOrgIDDevicesNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDevicesNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAccountOrIDUndefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDevicesNotSupplied
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDeviceNotSupplied
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAlreadyExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAccountOrNameUndefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceGroupMandatoryFieldsUndefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceHasImageUndefined
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DeviceHasNoImageUpdate
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DevicesHasMoreThanOneImageSet
=== RUN   TestDeviceNotFoundError/Testing_for_*services.ImageHasNoImageSet
=== RUN   TestDeviceNotFoundError/Testing_for_*services.CommitNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.CommitNotValid
=== RUN   TestDeviceNotFoundError/Testing_for_*services.OstreeNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.EntitiesImageSetsMismatch
=== RUN   TestDeviceNotFoundError/Testing_for_*services.CommitImageNotFound
=== RUN   TestDeviceNotFoundError/Testing_for_*services.SomeDevicesDoesNotExists
=== RUN   TestDeviceNotFoundError/Testing_for_*services.KafkaAllBrokersDown
=== RUN   TestDeviceNotFoundError/Testing_for_*services.DBCommitError
--- PASS: TestDeviceNotFoundError (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceNotFoundError (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.UpdateNotFoundError (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageNotFoundError (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageSetNotFoundError (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.AccountOrOrgIDNotSet (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.AccountNotSet (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.OrgIDNotSet (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.IDMustBeInteger (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryAlreadyExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryNameIsEmpty (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryURLIsEmpty (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryInfoIsInvalid (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.InvalidURLForCustomRepo (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ThirdPartyRepositoryImagesExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageVersionAlreadyExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageNameAlreadyExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.PackageNameDoesNotExist (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageNameUndefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageSetUnDefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageUnDefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageSetAlreadyExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageNotInErrorState (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupOrgIDDevicesNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDevicesNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAccountOrIDUndefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDevicesNotSupplied (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupDeviceNotSupplied (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAlreadyExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupAccountOrNameUndefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceGroupMandatoryFieldsUndefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceHasImageUndefined (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DeviceHasNoImageUpdate (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DevicesHasMoreThanOneImageSet (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.ImageHasNoImageSet (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.CommitNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.CommitNotValid (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.OstreeNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.EntitiesImageSetsMismatch (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.CommitImageNotFound (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.SomeDevicesDoesNotExists (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.KafkaAllBrokersDown (0.00s)
    --- PASS: TestDeviceNotFoundError/Testing_for_*services.DBCommitError (0.00s)
PASS
ok      github.com/redhatinsights/edge-api/pkg/services 0.546s
```

**Comment by omaciel** [comment]
Needs https://gitlab.cee.redhat.com/insights-qe/iqe-edge-plugin/-/merge_requests/569 to be merged as well.

@tomershinhar

**Comment by omaciel** [comment]
Screenshot 2022-11-26 at 19 03 25

**Comment by mgold1234** [comment]
@omaciel it looks like one automation test fail with this error:
assert ae.value.status == 404, f"Error- expected return code (404) but got {ae.value.status}"
12:05:41 >       assert "image is not found" in ae.value.body
12:05:41 E       assert 'image is not found' in '{"Code":"NOT_FOUND","Status":404,"Title":"image was not found"}\n'
12:05:41 E        +  where '{"Code":"NOT_FOUND","Status":404,"Title":"image was not found"}\n' = ApiException().body
12:05:41 E        +    where ApiException() = <ExceptionInfo ApiException() tblen=10>.value

12:05:41     @pytest.mark.parametrize("image_id", [99999999999, -1], ids=["large_id", "negative_id"])
12:05:41     def test_get_image_error_handling(api_client, image_id):
maybe need to fix this function test_get_image_error_handling(api_client, image_id):?

**Comment by omaciel** [comment]
@mgold1234 I can't check right now but I believe all tests should be fixed when https://gitlab.cee.redhat.com/insights-qe/iqe-edge-plugin/-/merge_requests/569 gets merged?

**Comment by mgold1234** [comment]
@omaciel yes you correct:)

**Review by tomershinhar — APPROVED** [review]
LGTM

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
