### PR TITLE
Images: FIXES images create function + validations.

### PR DESCRIPTION
**Pull request by ldjebran**
The validation that check image has been removed. And the new function that check name in the context of account has been enforced.

Fixes 

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
b5e55c22-b961-4270-9f19-60f2b85de947
ed308484-c3a8-4727-a46e-5b23df44a59f

**Review by acosferreira — APPROVED** [review]
lgtm

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
579717f2-99bf-47ad-8970-45db0dacfcbc
a3a35f1e-7e9e-4093-83d4-caa370deb4ee

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4168d808-4a8f-47a8-aa3b-cdfe57ee617b
ddababa5-29a8-40ed-bcbf-895e2b02a8f6

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
43b22e3c-410e-4b69-b0c9-d67f9291240e
c6f7cd0c-e54f-472b-8472-6590b2512f46

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
24316192-8b1f-423c-87f3-eb7c50b9aae5
bc6aa3a7-614d-4b7c-b5eb-1a90428c041e

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
03cf5dd4-c2f7-441b-8bff-884372e609c2
54054bcf-038b-4bbd-ae12-b119e9cd2c4f

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1dc2a979-cd99-469b-82db-dc495f8a7557
bd3c8499-a2f5-47ca-968d-00dcd8d02916

**Pull request merged**
