### PR TITLE
Temporarily suppress issues reported by "make pre-commit"

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

When documenting technical debt due to switch to golangci-lint, some files are reporting issues

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by de1987 — APPROVED** [review]

**Comment by omaciel** [comment]
Hmmm when I run `make pre-commit` locally, I don't see any issues. Out of curiosity, what are the things that `golang-ci` complain about `pkg/routes/storage.go`?

**Comment by omaciel** [comment]
To be honest I’d much rather have a list of tickets for us to address all of the code smells that are showing up now or we run the risk of continuously carrying this technical debt with us. As long as our PRs are not being blocked, how about we fix the issues instead as part of Sprint 53?

**Comment by thom-at-redhat** [comment]
@omaciel this was done as part of the overall approach to not carry technical debt.  I supplied the issues privately

**Review by omaciel — APPROVED** [review]
/lgtm

**Pull request merged**
