### PR TITLE
edge2261: remove extraneous event models

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Removing deprecated event model definitions and unused code.

Fixes # (issue) THEEDGE-2261

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by omaciel** [comment]
This PR deletes 108 lines of code and... we don't have unittests for this module?

**Comment by loadtheaccumulator** [comment]
> This PR deletes 108 lines of code and... we don't have unittests for this module?

These lines are related to the first pass struct for adopting the standard cloud event model and are no longer needed.
Tests for lines not covered in existing EDA code will be covered in subsequent PR(s) specific to tests.

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
