### PR TITLE
Remove org migrate files and call on main

### PR DESCRIPTION
**Pull request by adeliaferreira**
Signed-off-by: Adelia Ferreira <tay.figueira@gmail.com>

# Description

Task : 2689 
Removing unused org migrate files and remove call from migrate main file.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by AaronH88 — APPROVED** [review]
/lgtm

**Review by ldjebran — APPROVED** [review]

**Pull request merged**
