### PR TITLE
clowder images-build microservice config

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Adds a deployment for the images-build microservice.
Compiles the microservice and make executable available in the container.

Fixes # (issue) THEEDGE-2252

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Comment by loadtheaccumulator** [comment]
NOTE: PR #1290 MUST be merged first

**Review by thom-at-redhat — APPROVED** [review]

**Review by acosferreira — APPROVED** [review]
lgtm

**Pull request merged**
