### PR TITLE
Remove deprecated option and travis comments from mergify

### PR DESCRIPTION
**Pull request by thom-at-redhat**
# Description

1) Remove deprecated mergify option
2) Remove travis comments from mergify

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

yamllint + dashboard verification of configuration

### CODE REVIEW

**Review by acosferreira — APPROVED** [review]
lgtm

**Review by omaciel — APPROVED** [review]
/lgtm

**Pull request merged**
