### PR TITLE
fixed list-image-sets route count query

### PR DESCRIPTION
**Pull request by tomershinhar**
# Description

the count query needs to be updated as well to ignore deleted image-sets 

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

### CODE REVIEW

**Review by ldjebran — DISMISSED** [review]
/lgtm

**Review by ldjebran — APPROVED** [review]
/lgtm

**Review by acosferreira — APPROVED** [review]
/lgtm

**Comment by tomershinhar** [comment]
[@Mergifyio](https://github.com/Mergifyio) rebase

**Comment by tomershinhar** [comment]
@Mergifyio rebase

**Comment by omaciel** [comment]
@Mergifyio rebase

**Pull request merged**
