### PR TITLE
custom-repos: FIXES - route module.

### PR DESCRIPTION
**Pull request by ldjebran**
## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
83e5313a-5d59-4701-857a-5d301b811bc6
dce9f42d-fbb5-4b1c-956a-13f30ad0e2d5

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3bc212ff-7152-4121-9f45-fcaf9b7b0b4d
f0530c2d-fa5f-418c-846f-6150db908877

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
7a275526-9923-442f-a603-4898d101ddb6
c9144e26-750a-4ff8-a8bf-7fc2defcf1fd

**Review by AaronH88 — APPROVED** [review]
/lgtm

ok to merge

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Review by thom-at-redhat — APPROVED** [review]

**Comment by thom-at-redhat** [comment]
@mergify unqueue

**Comment by thom-at-redhat** [comment]
@mergifyio requeue

**Comment by thom-at-redhat** [comment]
@mergifyio refresh

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
085e7fbd-3e22-4c6e-a28d-3589902dcdd0
6ccb11b5-4f9a-45ec-b746-74f432ec34e6

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3d35b47f-e4ea-4b30-874a-de127f6e032e
5b2df22a-6266-427d-af7a-4f7f46380182

**Pull request merged**
