### PR TITLE
remove reboot playbook from dockerfile

### PR DESCRIPTION
**Pull request by loadtheaccumulator**
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

### CODE REVIEW

**Review by biancarosa — APPROVED** [review]
Might be worthy to also remove the code that calls it.

**Comment by loadtheaccumulator** [comment]
> Might be worthy to also remove the code that calls it.

Ah, yes. The call was removed before, but I can include removing the orphaned functions in this PR.

**Review by maxamillion — APPROVED** [review]

**Pull request merged**
